### ISSUE TITLE
Problem of RooExpensiveObjectCache

### ISSUE THREAD

**Issue by ram1123** [vukasinmilosevic/Fiducial_XS#12]
This is known issue as discussed here: https://root-forum.cern.ch/t/problems-rooexpensiveobjectcache/39456

It can be solved if we switch to ROOT 6.16. Currently, we are using ROOT 6.12.

Since our combine is using this version so its hard to switch now.

**Comment by ram1123** [comment]
If I understand correctly, this issue is mainly coming because we are using old workspace (.root) file.

So, we have to live with this issue until we don't replace the older workspace.

**Comment by vukasinmilosevic** [comment]
I think then we should proceed with the following:
1. For now we accept it that it is what it is, as it is only a warning from the usage of the old ws, but we don't close this issue.
2. If we have time during the analysis review, maybe we can focus on creating a non-template creation of ws in our workflow.

**Comment by ram1123** [comment]
#48 is going to resolve this issue. So, we can close this issue.

@vukasinmilosevic
