### ISSUE TITLE
Checking wether we use per channel shapes or combined for Z+X

### ISSUE THREAD

**Issue by vukasinmilosevic** [vukasinmilosevic/Fiducial_XS#18]
We need to confirm with LLR on what the approach is. Wether we use the combined 4l Z+X template file for all, or do we use per channel made ones.

https://github.com/vukasinmilosevic/Fiducial_XS/blob/ae5a818c843e86a171fdfe95bbe47ded431163ab/runHZZFiducialXS.py#L192-L195

**Comment by vukasinmilosevic** [comment]
@tjavaid  did you manage to check this after the meting? Leaving a tag for @ram1123 to be in the loop.

**Comment by tjavaid** [comment]
For HIG-19-001, we used channel wise templates files for Z+X for inclusive case. For differential variables, combined file (with AllChans tag) is used. This is how our workspace is also structured. However, from CJLST side I just checked the shapes for pT4l (0-10 bin), the shapes are different for each channel:

2e2mu: 
https://atarabin.web.cern.ch/atarabin/fiducial/run2_cardsValidation/pT4l/templatesBkgs_2018/XSTemplates_2e2mu_pT4l_2018_0_10_qqzz_ggzz_ZJetsCR.png

4e:
https://atarabin.web.cern.ch/atarabin/fiducial/run2_cardsValidation/pT4l/templatesBkgs_2018/XSTemplates_4e_pT4l_2018_0_10_qqzz_ggzz_ZJetsCR.png

4mu:
https://atarabin.web.cern.ch/atarabin/fiducial/run2_cardsValidation/pT4l/templatesBkgs_2018/XSTemplates_4mu_pT4l_2018_0_10_qqzz_ggzz_ZJetsCR.png

 But I am not sure whether they are actually using channel-wise in the workspace as well or using a conservative approach like us.

**Comment by vukasinmilosevic** [comment]
Ok, this is one thing that we need to agree on then with them. I'll note it down as a discussion point for our next meeting and will keep this issue open until it is settled.

**Comment by vukasinmilosevic** [comment]
After discussing it with the wider team, the conclusion is that we use per channel Z+X templates.
